import type { Driver, Team, Race, NewsItem } from './types';

export const TEAM_COLORS: Record<string, string> = {
  'McLaren': '#FF8000',
  'Ferrari': '#E8002D',
  'Red Bull': '#3671C6',
  'Mercedes': '#27F4D2',
  'Aston Martin': '#229971',
  'Williams': '#64C4FF',
  'Alpine': '#0093CC',
  'Audi': '#00877C',
  'Haas': '#B6BABD',
  'Racing Bulls': '#6692FF',
  'Cadillac': '#D9C27E',
};

export const DRIVERS: Driver[] = [
  {
    id: 'nor', pos: 1, name: 'Lando Norris', code: 'NOR', number: 1, team: 'McLaren',
    country: '🇬🇧', pts: 60, gap: 'LEADER', color: TEAM_COLORS['McLaren'],
    bio: 'The reigning World Champion has carried 2025 form into the new regulation era. The MCL40 is the most balanced car of the 11-team grid and Norris has converted that into the early championship lead.',
    careerStats: { wins: 12, podiums: 41, titles: 1, races: 145 }, posChange: 0,
  },
  {
    id: 'pia', pos: 2, name: 'Oscar Piastri', code: 'PIA', number: 81, team: 'McLaren',
    country: '🇦🇺', pts: 53, gap: -7, color: TEAM_COLORS['McLaren'],
    bio: 'Year four at McLaren. A Japan win, Australia podium, and the cooler head in tight battles. Currently splitting the team-mate fight in his favour on race pace.',
    careerStats: { wins: 6, podiums: 24, titles: 0, races: 91 }, posChange: 1,
  },
  {
    id: 'ver', pos: 3, name: 'Max Verstappen', code: 'VER', number: 3, team: 'Red Bull',
    country: '🇳🇱', pts: 48, gap: -12, color: TEAM_COLORS['Red Bull'],
    bio: 'The four-time champion has dropped the #1 to take #3 in the new era. The RB22 has not extracted the new power unit as cleanly as McLaren but Verstappen remains the closest non-papaya threat.',
    careerStats: { wins: 67, podiums: 117, titles: 4, races: 222 }, posChange: -1,
  },
  {
    id: 'lec', pos: 4, name: 'Charles Leclerc', code: 'LEC', number: 16, team: 'Ferrari',
    country: '🇲🇨', pts: 41, gap: -19, color: TEAM_COLORS['Ferrari'],
    bio: 'The senior Ferrari driver has rebuilt the SF-26 setup around his front-end demands. The car finally rotates and the early podiums show it.',
    careerStats: { wins: 9, podiums: 45, titles: 0, races: 158 }, posChange: 0,
  },
  {
    id: 'ham', pos: 5, name: 'Lewis Hamilton', code: 'HAM', number: 44, team: 'Ferrari',
    country: '🇬🇧', pts: 35, gap: -25, color: TEAM_COLORS['Ferrari'],
    bio: 'Year two in red. Hamilton is more comfortable with the SF-26 than the SF-25 and has out-qualified Leclerc once. The pursuit of an eighth title is alive.',
    careerStats: { wins: 105, podiums: 205, titles: 7, races: 369 }, posChange: 0,
  },
  {
    id: 'rus', pos: 6, name: 'George Russell', code: 'RUS', number: 63, team: 'Mercedes',
    country: '🇬🇧', pts: 30, gap: -30, color: TEAM_COLORS['Mercedes'],
    bio: 'Mercedes are back in the picture with the new power unit. Russell has converted that into a podium and steady top-five finishes.',
    careerStats: { wins: 4, podiums: 20, titles: 0, races: 140 }, posChange: 0,
  },
  {
    id: 'ant', pos: 7, name: 'Andrea Kimi Antonelli', code: 'ANT', number: 12, team: 'Mercedes',
    country: '🇮🇹', pts: 22, gap: -38, color: TEAM_COLORS['Mercedes'],
    bio: 'Year two for Antonelli. The Italian has matured into a consistent points scorer and out-paced Russell in qualifying twice already.',
    careerStats: { wins: 0, podiums: 2, titles: 0, races: 31 }, posChange: 0,
  },
  {
    id: 'alo', pos: 8, name: 'Fernando Alonso', code: 'ALO', number: 14, team: 'Aston Martin',
    country: '🇪🇸', pts: 18, gap: -42, color: TEAM_COLORS['Aston Martin'],
    bio: 'Newey-led Aston Martin has built a competitive package and Alonso is extracting every ounce. A podium in Australia signalled intent.',
    careerStats: { wins: 32, podiums: 107, titles: 2, races: 416 }, posChange: 1,
  },
  {
    id: 'sai', pos: 9, name: 'Carlos Sainz', code: 'SAI', number: 55, team: 'Williams',
    country: '🇪🇸', pts: 15, gap: -45, color: TEAM_COLORS['Williams'],
    bio: 'Sainz is delivering on the Williams gamble. The FW48 has strong race pace and the Spaniard has scored in every points-paying race so far.',
    careerStats: { wins: 4, podiums: 27, titles: 0, races: 222 }, posChange: 0,
  },
  {
    id: 'alb', pos: 10, name: 'Alex Albon', code: 'ALB', number: 23, team: 'Williams',
    country: '🇹🇭', pts: 12, gap: -48, color: TEAM_COLORS['Williams'],
    bio: 'Albon continues to extract midfield podium contention from the Williams package and has out-qualified Sainz once already.',
    careerStats: { wins: 0, podiums: 2, titles: 0, races: 111 }, posChange: 0,
  },
  {
    id: 'gas', pos: 11, name: 'Pierre Gasly', code: 'GAS', number: 10, team: 'Alpine',
    country: '🇫🇷', pts: 10, gap: -50, color: TEAM_COLORS['Alpine'],
    bio: 'Alpine\'s reset year is starting to bear fruit. Gasly leads the team\'s recovery with a steady run of points.',
    careerStats: { wins: 1, podiums: 5, titles: 0, races: 175 }, posChange: 0,
  },
  {
    id: 'had', pos: 12, name: 'Isack Hadjar', code: 'HAD', number: 6, team: 'Red Bull',
    country: '🇫🇷', pts: 8, gap: -52, color: TEAM_COLORS['Red Bull'],
    bio: 'Promoted from Racing Bulls to partner Verstappen. A bruising baptism alongside the four-time champion but the speed has been there.',
    careerStats: { wins: 0, podiums: 0, titles: 0, races: 28 }, posChange: 5,
  },
  {
    id: 'per', pos: 13, name: 'Sergio Perez', code: 'PER', number: 11, team: 'Cadillac',
    country: '🇲🇽', pts: 7, gap: -53, color: TEAM_COLORS['Cadillac'],
    bio: 'The Mexican veteran has returned with the new American factory entry. Cadillac\'s debut package is competitive and Perez has scored in two of three rounds.',
    careerStats: { wins: 6, podiums: 39, titles: 0, races: 281 }, posChange: 0,
  },
  {
    id: 'bot', pos: 14, name: 'Valtteri Bottas', code: 'BOT', number: 77, team: 'Cadillac',
    country: '🇫🇮', pts: 5, gap: -55, color: TEAM_COLORS['Cadillac'],
    bio: 'Back on the grid with Cadillac. The 10-time race winner brings development experience the new team badly needed and is repaying it with consistent finishes.',
    careerStats: { wins: 10, podiums: 67, titles: 0, races: 248 }, posChange: 0,
  },
  {
    id: 'bor', pos: 15, name: 'Gabriel Bortoleto', code: 'BOR', number: 5, team: 'Audi',
    country: '🇧🇷', pts: 4, gap: -56, color: TEAM_COLORS['Audi'],
    bio: 'Year two for the 2024 F2 champion. Audi\'s engine programme is showing real top-end speed and Bortoleto has converted that into points already.',
    careerStats: { wins: 0, podiums: 0, titles: 0, races: 28 }, posChange: 1,
  },
  {
    id: 'hul', pos: 16, name: 'Nico Hülkenberg', code: 'HUL', number: 27, team: 'Audi',
    country: '🇩🇪', pts: 3, gap: -57, color: TEAM_COLORS['Audi'],
    bio: 'Senior driver at the Audi factory entry. A lone points finish in Japan has him narrowly behind his team-mate.',
    careerStats: { wins: 0, podiums: 1, titles: 0, races: 250 }, posChange: -1,
  },
  {
    id: 'oco', pos: 17, name: 'Esteban Ocon', code: 'OCO', number: 31, team: 'Haas',
    country: '🇫🇷', pts: 2, gap: -58, color: TEAM_COLORS['Haas'],
    bio: 'Senior driver at Haas. A lone points finish in Australia is the highlight of a difficult start.',
    careerStats: { wins: 1, podiums: 4, titles: 0, races: 180 }, posChange: 0,
  },
  {
    id: 'bea', pos: 18, name: 'Oliver Bearman', code: 'BEA', number: 87, team: 'Haas',
    country: '🇬🇧', pts: 1, gap: -59, color: TEAM_COLORS['Haas'],
    bio: 'Year two at Haas. Sharp qualifying speed but race-day luck has been thin.',
    careerStats: { wins: 0, podiums: 0, titles: 0, races: 30 }, posChange: 0,
  },
  {
    id: 'lin', pos: 19, name: 'Arvid Lindblad', code: 'LIN', number: 41, team: 'Racing Bulls',
    country: '🇬🇧', pts: 1, gap: -59, color: TEAM_COLORS['Racing Bulls'],
    bio: 'The British-Swedish 2025 F2 graduate makes his F1 debut with Racing Bulls. A points finish on debut weekend in Australia signalled the talent.',
    careerStats: { wins: 0, podiums: 0, titles: 0, races: 3 }, posChange: 1,
  },
  {
    id: 'law', pos: 20, name: 'Liam Lawson', code: 'LAW', number: 30, team: 'Racing Bulls',
    country: '🇳🇿', pts: 0, gap: -60, color: TEAM_COLORS['Racing Bulls'],
    bio: 'Returned to Racing Bulls after his short Red Bull stint. Working to rebuild form and finding the rookie team-mate sharp.',
    careerStats: { wins: 0, podiums: 0, titles: 0, races: 26 }, posChange: -1,
  },
  {
    id: 'str', pos: 21, name: 'Lance Stroll', code: 'STR', number: 18, team: 'Aston Martin',
    country: '🇨🇦', pts: 0, gap: -60, color: TEAM_COLORS['Aston Martin'],
    bio: 'Comprehensively out-paced by Alonso again. No points yet from three rounds.',
    careerStats: { wins: 0, podiums: 3, titles: 0, races: 201 }, posChange: -2,
  },
  {
    id: 'col', pos: 22, name: 'Franco Colapinto', code: 'COL', number: 43, team: 'Alpine',
    country: '🇦🇷', pts: 0, gap: -60, color: TEAM_COLORS['Alpine'],
    bio: 'A pointless start to a full Alpine season. The qualifying pace is there but race day has not yet delivered.',
    careerStats: { wins: 0, podiums: 0, titles: 0, races: 35 }, posChange: 0,
  },
];

export const TEAMS: Team[] = [
  { id: 'mclaren',      pos: 1,  name: 'McLaren',      engine: 'Mercedes', country: '🇬🇧', pts: 113, color: TEAM_COLORS['McLaren'],      posChange: 0 },
  { id: 'ferrari',      pos: 2,  name: 'Ferrari',      engine: 'Ferrari',  country: '🇮🇹', pts: 76,  color: TEAM_COLORS['Ferrari'],      posChange: 0 },
  { id: 'red-bull',     pos: 3,  name: 'Red Bull',     engine: 'Ford',     country: '🇦🇹', pts: 56,  color: TEAM_COLORS['Red Bull'],     posChange: 0 },
  { id: 'mercedes',     pos: 4,  name: 'Mercedes',     engine: 'Mercedes', country: '🇩🇪', pts: 52,  color: TEAM_COLORS['Mercedes'],     posChange: 0 },
  { id: 'williams',     pos: 5,  name: 'Williams',     engine: 'Mercedes', country: '🇬🇧', pts: 27,  color: TEAM_COLORS['Williams'],     posChange: 1 },
  { id: 'aston-martin', pos: 6,  name: 'Aston Martin', engine: 'Honda',    country: '🇬🇧', pts: 18,  color: TEAM_COLORS['Aston Martin'], posChange: -1 },
  { id: 'cadillac',     pos: 7,  name: 'Cadillac',     engine: 'Ferrari',  country: '🇺🇸', pts: 12,  color: TEAM_COLORS['Cadillac'],     posChange: 0 },
  { id: 'alpine',       pos: 8,  name: 'Alpine',       engine: 'Renault',  country: '🇫🇷', pts: 10,  color: TEAM_COLORS['Alpine'],       posChange: 0 },
  { id: 'audi',         pos: 9,  name: 'Audi',         engine: 'Audi',     country: '🇩🇪', pts: 7,   color: TEAM_COLORS['Audi'],         posChange: 0 },
  { id: 'haas',         pos: 10, name: 'Haas',         engine: 'Ferrari',  country: '🇺🇸', pts: 3,   color: TEAM_COLORS['Haas'],         posChange: 0 },
  { id: 'racing-bulls', pos: 11, name: 'Racing Bulls', engine: 'Ford',     country: '🇮🇹', pts: 1,   color: TEAM_COLORS['Racing Bulls'], posChange: 0 },
];

export const CALENDAR: Race[] = [
  {
    round: 1, country: 'Australia', flag: '🇦🇺', circuit: 'Albert Park Circuit', circuitId: 'melbourne',
    date: '2026-03-08', location: 'Melbourne', laps: 58, distance: '306.124 km',
    isDone: true, winner: 'Lando Norris', weather: 'Dry · 21°C',
    podiumDetailed: [
      { driver: 'NOR', team: 'McLaren',      gap: '+0.000' },
      { driver: 'PIA', team: 'McLaren',      gap: '+2.910' },
      { driver: 'ALO', team: 'Aston Martin', gap: '+11.502' },
    ],
    fastestLap: { driver: 'PIA', time: '1:18.991' },
    tyreCompounds: ['soft', 'medium', 'hard'],
  },
  {
    round: 2, country: 'China', flag: '🇨🇳', circuit: 'Shanghai International Circuit', circuitId: 'shanghai',
    date: '2026-03-15', location: 'Shanghai', laps: 56, distance: '305.066 km',
    isDone: true, winner: 'Oscar Piastri', weather: 'Dry · 24°C',
    podiumDetailed: [
      { driver: 'PIA', team: 'McLaren',  gap: '+0.000' },
      { driver: 'NOR', team: 'McLaren',  gap: '+3.108' },
      { driver: 'HAM', team: 'Ferrari',  gap: '+9.667' },
    ],
    fastestLap: { driver: 'NOR', time: '1:32.008' },
    tyreCompounds: ['soft', 'medium'],
  },
  {
    round: 3, country: 'Japan', flag: '🇯🇵', circuit: 'Suzuka International Racing Course', circuitId: 'suzuka',
    date: '2026-03-29', location: 'Suzuka', laps: 53, distance: '307.471 km',
    isDone: true, winner: 'Oscar Piastri', weather: 'Dry · 18°C',
    podiumDetailed: [
      { driver: 'PIA', team: 'McLaren',   gap: '+0.000' },
      { driver: 'VER', team: 'Red Bull',  gap: '+0.812' },
      { driver: 'LEC', team: 'Ferrari',   gap: '+6.221' },
    ],
    fastestLap: { driver: 'VER', time: '1:30.412' },
    tyreCompounds: ['medium', 'hard'],
  },
  {
    round: 4, country: 'United States', flag: '🇺🇸', circuit: 'Miami International Autodrome', circuitId: 'miami',
    date: '2026-05-03', location: 'Miami', laps: 57, distance: '308.326 km',
    isNext: true,
    sessions: [
      { type: 'FP1',                date: '2026-05-01', time: '12:30 ET', status: 'completed' },
      { type: 'Sprint Qualifying',  date: '2026-05-01', time: '16:30 ET', status: 'completed' },
      { type: 'Sprint',             date: '2026-05-02', time: '12:00 ET', status: 'completed' },
      { type: 'Qualifying',         date: '2026-05-02', time: '16:00 ET', status: 'completed' },
      { type: 'Race',               date: '2026-05-03', time: '16:00 ET', status: 'live' },
    ],
  },
  { round: 5,  country: 'Canada',         flag: '🇨🇦', circuit: 'Circuit Gilles Villeneuve',     circuitId: 'montreal',    date: '2026-05-24', location: 'Montréal' },
  { round: 6,  country: 'Monaco',         flag: '🇲🇨', circuit: 'Circuit de Monaco',             circuitId: 'monaco',      date: '2026-06-07', location: 'Monte Carlo' },
  { round: 7,  country: 'Catalunya',      flag: '🇪🇸', circuit: 'Circuit de Barcelona-Catalunya',circuitId: 'barcelona',   date: '2026-06-14', location: 'Barcelona' },
  { round: 8,  country: 'Austria',        flag: '🇦🇹', circuit: 'Red Bull Ring',                 circuitId: 'spielberg',   date: '2026-06-28', location: 'Spielberg' },
  { round: 9,  country: 'United Kingdom', flag: '🇬🇧', circuit: 'Silverstone Circuit',           circuitId: 'silverstone', date: '2026-07-05', location: 'Silverstone' },
  { round: 10, country: 'Belgium',        flag: '🇧🇪', circuit: 'Circuit de Spa-Francorchamps',  circuitId: 'spa',         date: '2026-07-19', location: 'Spa' },
  { round: 11, country: 'Hungary',        flag: '🇭🇺', circuit: 'Hungaroring',                   circuitId: 'hungary',     date: '2026-07-26', location: 'Budapest' },
  { round: 12, country: 'Netherlands',    flag: '🇳🇱', circuit: 'Circuit Zandvoort',             circuitId: 'zandvoort',   date: '2026-08-23', location: 'Zandvoort' },
  { round: 13, country: 'Italy',          flag: '🇮🇹', circuit: 'Autodromo Nazionale Monza',     circuitId: 'monza',       date: '2026-09-06', location: 'Monza' },
  { round: 14, country: 'Spain',          flag: '🇪🇸', circuit: 'Madring (Circuito IFEMA Madrid)', circuitId: 'madrid',    date: '2026-09-13', location: 'Madrid' },
  { round: 15, country: 'Azerbaijan',     flag: '🇦🇿', circuit: 'Baku City Circuit',             circuitId: 'baku',        date: '2026-09-26', location: 'Baku' },
  { round: 16, country: 'Singapore',      flag: '🇸🇬', circuit: 'Marina Bay Street Circuit',     circuitId: 'singapore',   date: '2026-10-11', location: 'Singapore' },
  { round: 17, country: 'United States',  flag: '🇺🇸', circuit: 'Circuit of the Americas',       circuitId: 'cota',        date: '2026-10-25', location: 'Austin' },
  { round: 18, country: 'Mexico',         flag: '🇲🇽', circuit: 'Autódromo Hermanos Rodríguez',  circuitId: 'mexico',      date: '2026-11-01', location: 'Mexico City' },
  { round: 19, country: 'Brazil',         flag: '🇧🇷', circuit: 'Interlagos',                    circuitId: 'interlagos',  date: '2026-11-08', location: 'São Paulo' },
  { round: 20, country: 'United States',  flag: '🇺🇸', circuit: 'Las Vegas Strip Circuit',       circuitId: 'lasvegas',    date: '2026-11-21', location: 'Las Vegas' },
  { round: 21, country: 'Qatar',          flag: '🇶🇦', circuit: 'Lusail International Circuit',  circuitId: 'lusail',      date: '2026-11-29', location: 'Lusail' },
  { round: 22, country: 'Abu Dhabi',      flag: '🇦🇪', circuit: 'Yas Marina Circuit',            circuitId: 'yasmarina',   date: '2026-12-06', location: 'Abu Dhabi' },
];

export const NEWS: NewsItem[] = [
  { id: 1, kicker: 'STRATEGY', headline: 'Norris carries title form into the new regulation era', body: 'Three rounds in and the reigning World Champion is doing what champions do. Norris leads Piastri by seven points and Verstappen by twelve, with the MCL40 looking like the most balanced car of the new generation. McLaren\'s active aero calibration responds 0.04 seconds faster to throttle inputs than any rival, buying the team three to five tenths a lap on medium-speed corners.', type: 'lead' },
  { id: 2, kicker: 'PADDOCK', headline: 'Cadillac\'s F1 debut: Perez and Bottas in the points', body: 'The American factory entry has answered every doubt about its debut readiness. Perez has scored in two of three rounds, Bottas in one, and the Ferrari-powered chassis has out-qualified both Audi and Haas at every venue. The next test is whether the development rate can keep pace through the European leg.' },
  { id: 3, kicker: 'TECHNICAL', headline: 'The MGU-K Hybrid+ is reshaping race strategy', body: 'The retirement of the MGU-H and the move to a 50/50 power split has changed the calculus on energy deployment. Teams are now front-loading electrical boost into qualifying and managing carefully across stints. Ferrari\'s SF-26 is reported to have the most efficient deployment software in the field.' },
  { id: 4, kicker: 'DRIVER', headline: 'Hadjar finds Red Bull a steeper climb than expected', body: 'Promoted from Racing Bulls, Hadjar is learning the RB22 the hard way. Eight points to Verstappen\'s forty-eight after three rounds. The pace is there in qualifying but the race-day execution has not yet matched the senior driver.' },
  { id: 5, kicker: 'REGULATION', headline: 'Active aero working as advertised — for some', body: 'The new movable wings have produced clean overtakes and tight racing in the opening triple-header. But teams that misread the activation logic in qualifying have lost up to two tenths a lap. McLaren and Ferrari have led on this front; Audi and Haas are still calibrating.' },
];

export const DRIVER_NUMBER_MAP: Record<number, string> = {
  1: 'nor', 81: 'pia',
  3: 'ver', 6: 'had',
  16: 'lec', 44: 'ham',
  63: 'rus', 12: 'ant',
  14: 'alo', 18: 'str',
  55: 'sai', 23: 'alb',
  10: 'gas', 43: 'col',
  31: 'oco', 87: 'bea',
  27: 'hul', 5: 'bor',
  41: 'lin', 30: 'law',
  11: 'per', 77: 'bot',
};
